config/routes.rb
Shoppe::Engine.routes.draw do
  resources :subscription_plans do
    resources :subscribers
    collection do
      get 'sync'
      patch 'stripe_account'
    end
  end
end

app/models/concerns/shoppe/api_handler.rb
require 'stripe'

module Shoppe
  module ApiHandler
    extend ActiveSupport::Concern

    INTERVALS = [:day, :month, :week, :year]

    included do
      after_create :create_stripe_entity
      after_update :update_stripe_entity
      before_destroy :delete_stripe_entity
    end

    def self.get_currencies(api_key = nil)
      # As of Stripe API version '2015-10-16' we need to get the account country then the country spec
      account = ::Stripe::Account.retrieve(key(api_key))
      country_spec = ::Stripe::CountrySpec.retrieve(account.country, key(api_key))
      country_spec.supported_payment_currencies
    end

    def self.get_subscription_plans(api_key = nil)
      ::Stripe::Plan.all({}, key(api_key))
    end

    def self.native_amount(amount)
      amount / 100.0
    end

    def self.key(api_key)
      api_key || @stripe_api_key || Shoppe::Stripe.api_key
    end

    def key(api_key)
      api_key || @stripe_api_key || Shoppe::Stripe.api_key
    end

    private

    def retrieve_api_plan(plan_id, api_key = nil)
      ::Stripe::Plan.retrieve(plan_id, key(api_key))
    end

    def retrieve_subscription(stripe_id, api_key = nil)
      ::Stripe::Subscription.retrieve(stripe_id, key(api_key))
    end

    def stripe_amount(amount)
      (amount * 100).to_i
    end
  end
end

app/models/shoppe/gift.rb
module Shoppe
  class Gift < ActiveRecord::Base
    belongs_to :product, class_name: 'Shoppe::Product'
    belongs_to :subscriber, class_name: 'Shoppe::Subscriber'

    scope :unclaimed, -> { where(claimed: false) }
  end
end

app/models/shoppe/subscriber.rb
module Shoppe
  class Subscriber < ActiveRecord::Base
    include ApiHandler

    belongs_to :subscription_plan, class_name: 'Shoppe::SubscriptionPlan'

    belongs_to :customer, class_name: 'Shoppe::Customer'

    has_many :transactions, class_name: 'Shoppe::SubscriberTransaction'

    has_many :gifts, class_name: 'Shoppe::Gift', inverse_of: :subscriber

    default_scope { where(cancelled_at: nil) }

    attr_accessor :stripe_api_key

    private

    def create_stripe_entity(_api_key = nil)
      Rails.logger.warn 'Creation of Subscribers from Shoppe interface is not currently supported'
    end

    def delete_stripe_entity(api_key = nil)
      subscription = retrieve_subscription(stripe_id, api_key)
      subscription.delete
    end

    def update_stripe_entity(api_key = nil)
      if cancelled_at_changed? and cancelled_at.present?
        delete_stripe_entity(api_key)
      end
    end
  end
end

app/models/shoppe/subscriber_transaction.rb
module Shoppe
  class SubscriberTransaction < ActiveRecord::Base

    TYPES = ['invoice']

    belongs_to :subscriber
  end
end

app/models/shoppe/subscription_plan.rb
module Shoppe
  class SubscriptionPlan < ActiveRecord::Base
    include ApiHandler

    self.table_name = 'shoppe_subscription_plans'

    # Validations
    validates :name, presence: true
    validates :amount, presence: true
    validates :interval, presence: true

    belongs_to :product, class_name: 'Shoppe::Product'

    has_many :subscribers, class_name: 'Shoppe::Subscriber'

    attr_accessor :stripe_api_key

    def cancelled_subscribers
      subscribers.unscoped.where(subscription_plan_id: id).where.not(cancelled_at: nil)
    end

    private

    def create_stripe_entity(api_key = nil)
      ::Stripe::Plan.create({
                                amount: stripe_amount(amount),
                                interval: interval,
                                interval_count: interval_count,
                                name: name,
                                currency: currency,
                                id: api_plan_id,
                                trial_period_days: trial_period_days
                            }, self.key(api_key))
    rescue ::Stripe::InvalidRequestError
      Rails.logger.info 'Stripe plan already exists!'
    end

    def delete_stripe_entity(api_key = nil)
      stripe_plan = retrieve_api_plan(api_plan_id, api_key)
      stripe_plan.delete
    end

    def update_stripe_entity(api_key = nil)
      if name_changed?
        stripe_plan = retrieve_api_plan(api_plan_id, api_key)
        stripe_plan.name = name
        stripe_plan.save
      end
    end
  end
end

app/controllers/shoppe/subscribers_controller.rb
module Shoppe
  class SubscribersController < Shoppe::ApplicationController
    before_action :set_subscriber, only: [:show, :edit, :update, :destroy]
    before_action :set_subscription_plan

    # GET /subscribers
    def index
      @subscribers = @subscription_plan.subscribers
      @cancelled_subscribers = @subscription_plan.cancelled_subscribers
    end

    # GET /subscribers/1
    def show
    end

    # GET /subscribers/new
    def new
      @subscriber = Subscriber.new
    end

    # GET /subscribers/1/edit
    def edit
    end

    # POST /subscribers
    def create
      @subscriber = Subscriber.new(subscriber_params)

      if @subscriber.save
        redirect_to @subscriber, notice: t('shoppe.subscribers.create_notice')
      else
        render :new
      end
    end

    # PATCH/PUT /subscribers/1
    def update
      if @subscriber.update(subscriber_params)
        redirect_to [@subscription_plan, :subscribers], notice: t('shoppe.subscribers.update_notice')
      else
        render :edit
      end
    end

    # DELETE /subscribers/1
    def destroy
      @subscriber.update_attribute(:cancelled_at, DateTime.now)
      redirect_to [@subscription_plan, :subscribers], notice: t('shoppe.subscribers.cancelled_notice')
    end

    private

      # Use callbacks to share common setup or constraints between actions.
      def set_subscriber
        @subscriber = Subscriber.unscoped.find(params[:id])

        # Also set the Stripe API Key for API actions on this subscriber
        @subscriber.stripe_api_key = ENV[session[:stripe_account]]
      end

      def set_subscription_plan
        @subscription_plan = SubscriptionPlan.find(params[:subscription_plan_id])
      end

      # Only allow a trusted parameter "white list" through.
      def subscriber_params
        params.require(:subscriber).permit(:subscriber_plan_id, :customer_id, :recipient_name, :balance, :stripe_id)
      end
  end
end

app/controllers/shoppe/subscription_plans_controller.rb
module Shoppe
  class SubscriptionPlansController < Shoppe::ApplicationController
    before_action :set_stripe_account
    before_action :set_subscription_plan, only: [:show, :edit, :update, :destroy]

    before_filter { @active_nav = :subscription_plans }
    # before_filter { params[:id] && @subscription_plan = Shoppe::SubscriptionPlan.find(params[:id]) }

    # GET /subscription_plans
    def index
      @subscription_plans = Shoppe::SubscriptionPlan.all
    end

    # GET /subscription_plans/1
    def show
    end

    # GET /subscription_plans/new
    def new
      @subscription_plan = Shoppe::SubscriptionPlan.new
      @subscribable_products = Shoppe::Product.active.with_attributes('subscription', 'true')
      begin
        @charging_currencies = Shoppe::ApiHandler.get_currencies(ENV[session[:stripe_account]])
      rescue ::Stripe::InvalidRequestError
        flash[:warning] = t('shoppe.subscription_plans.api_responses.currency_retrieval_failed')
        @charging_currencies = []
      end
    end

    # GET /subscription_plans/1/edit
    def edit
      @subscribable_products = Shoppe::Product.active.with_attributes('subscription', 'true')
      begin
        @charging_currencies = Shoppe::ApiHandler.get_currencies(ENV[session[:stripe_account]])
      rescue ::Stripe::InvalidRequestError
        flash[:warning] = t('shoppe.subscription_plans.api_responses.currency_retrieval_failed')
        @charging_currencies = []
      end
    end

    # POST /subscription_plans
    def create
      begin
        extra = {stripe_api_key: ENV[@stripe_account]}
        @subscription_plan = Shoppe::SubscriptionPlan.new(subscription_plan_params.merge(extra))
      rescue ::Stripe::InvalidRequestError => e
        flash[:warning] = e.message
      end

      if @subscription_plan.save
        redirect_to @subscription_plan, notice: t('shoppe.subscription_plans.api_responses.plan_created')
      else
        render :new
      end
    end

    # PATCH/PUT /subscription_plans/1
    def update
      # Only name can be updated as that is what our payment provider (stripe) allows.
      # FIXME We need to add statement_descriptor as that can be updated too
      if @subscription_plan.update_attributes subscription_plan_params
        redirect_to @subscription_plan, notice: t('shoppe.subscription_plans.api_responses.plan_updated')
      else
        render :edit
      end
    end

    # DELETE /subscription_plans/1
    def destroy
      @subscription_plan.destroy
      redirect_to subscription_plans_url, notice: t('shoppe.subscription_plans.api_responses.plan_destroyed')
    end

    # SYNC with plans provider
    def sync
      # Get all API plans for all known Stripe accounts
      ENV.keys.each do |key|
        if key.start_with? 'STRIPE_API_KEY'
          name = get_stripe_account_id(key)
          logger.debug "Loading Stripe subscription plans for account: #{name} (#{key})"
          sync_plans(ENV[key])
        end
      end

      redirect_to subscription_plans_url, notice: t('shoppe.subscription_plans.api_responses.sync_complete')
    end

    def stripe_account
      # Switch Stripe account
      session[:stripe_account] = params[:stripe_account]
      logger.debug "Shoppe::SubscriptionPlansController user set Stripe account to #{session[:stripe_account]}"
      redirect_to request.referer
    end

    private

    def sync_plans(stripe_api_key)
      begin
        @external_plans = Shoppe::ApiHandler.get_subscription_plans(stripe_api_key)
        @external_plans.data.each do |external_plan|
          shoppe_plan = Shoppe::SubscriptionPlan.find_or_create_by(api_plan_id: external_plan.id, currency: external_plan.currency)
          shoppe_plan.amount = Shoppe::ApiHandler.native_amount(external_plan.amount)
          shoppe_plan.interval = external_plan.interval
          shoppe_plan.interval_count = external_plan.interval_count
          shoppe_plan.name = external_plan.name
          shoppe_plan.trial_period_days = external_plan.trial_period_days || 0
          shoppe_plan.stripe_api_key = stripe_api_key
          shoppe_plan.save
        end
      rescue ::Stripe::InvalidRequestError
        flash[:warning] = t('shoppe.subscription_plans.api_responses.plan_sync_failed')
      end
    end

    def get_stripe_account_id(api_key_name)
      matches = api_key_name.match(/STRIPE_API_KEY(_(\w+))?/)
      matches[2] || 'default'
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_subscription_plan
      @subscription_plan = Shoppe::SubscriptionPlan.find(params[:id])

      # Also set the Stripe API Key for API actions on this subscriber
      @subscription_plan.stripe_api_key = ENV[@stripe_account]
    end

    def set_stripe_account
      @stripe_accounts = ['STRIPE_API_KEY', 'STRIPE_API_KEY_US']
      session[:stripe_account] = @stripe_accounts[0] if session[:stripe_account].blank?
      @stripe_account = session[:stripe_account]
      logger.debug "Shoppe::SubscriptionPlans Stripe account is #{session[:stripe_account]}"
    end

    # Only allow a trusted parameter "white list" through.
    def subscription_plan_params
      params.require(:subscription_plan).permit(:amount, :interval, :interval_count, :name, :currency, :trial_period_days, :api_plan_id, :product_id)
    end
  end
end

app/helpers/shoppe/subscription_plans_helper.rb
module Shoppe
  module SubscriptionPlansHelper
  end
end

app/views/shoppe/subscription_plans/_form.html.haml
= stylesheet_link_tag 'shoppe_subscriptions/application'
= javascript_include_tag 'shoppe_subscriptions/application'

= form_for @subscription_plan do |f|
  = f.error_messages

  = field_set_tag  t('shoppe.subscription_plans.summary') do
    .splitContainer
      %dl.half
        %dt= f.label :name,  t('shoppe.subscription_plans.name')
        %dd= f.text_field :name, :class => 'text'
      %dl.half
        %dt= f.label :api_plan_id,  t('shoppe.subscription_plans.api_plan_id')
        %dd
          = f.text_field :api_plan_id, {:class => 'text', readonly: @subscription_plan.persisted?}
          %p.help=  t('shoppe.subscription_plans.stripe_subscription_plan_id')

  = field_set_tag t('shoppe.subscription_plans.price') do
    .splitContainer
      %dl.third
        %dt= f.label :amount, t('shoppe.subscription_plans.amount')
        %dd
          = f.text_field :amount, readonly: @subscription_plan.persisted?, :class => 'text'
      %dl.third
        %dt= f.label :currency, t('shoppe.subscription_plans.currency')
        %dd
          = f.select :currency, @charging_currencies, {disabled: @subscription_plan.persisted?}, {class: 'chosen', disabled: @subscription_plan.persisted?}
          %p.help=  t('shoppe.subscription_plans.currency_help')
      %dl.third
        %dt= f.label :trial_period_days, t('shoppe.subscription_plans.trial_period_days')
        %dd
          = f.text_field :trial_period_days, {class: 'text', placeholder: t('shoppe.subscription_plans.days').downcase, readonly: @subscription_plan.persisted?}
          %p.help=  t('shoppe.subscription_plans.trial_period_help')

  = field_set_tag t('shoppe.subscription_plans.interval') do
    .splitContainer
      %dl.half
        %dt= f.label :interval, t('shoppe.subscription_plans.interval')
        %dd
          = f.select :interval, Shoppe::SubscriptionPlan::INTERVALS.collect {|i| [t("shoppe.intervals.#{i}"), i]}, {}, {class: 'chosen', disabled: @subscription_plan.persisted?}
          %p.help=  t('shoppe.subscription_plans.interval_help')
      %dl.half
        %dt= f.label :interval_count, t('shoppe.subscription_plans.interval_count')
        %dd
          = f.text_field :interval_count, {:class => 'text', readonly: @subscription_plan.persisted?}
          %p.help=  t('shoppe.subscription_plans.interval_count_help')

  = field_set_tag t('shoppe.subscription_plans.product') do
    .container
      %dl
        %dt= f.label :product, t('shoppe.subscription_plans.product')
        %dd
          = f.collection_select :product_id, @subscribable_products, :id, :full_name, {include_blank: true}, {class: 'chosen-with-deselect', data: {placeholder: t('shoppe.subscription_plans.select_product')}}

  %p.submit
    - unless @subscription_plan.new_record?
      %span.right= link_to  t('shoppe.delete'), [@subscription_plan], :class => 'button purple', :method => :delete, :data => {:confirm => t('shoppe.subscription_plans.delete_confirmation')}
    = f.submit t('shoppe.submit'), :class => 'button green'
    = link_to t('shoppe.cancel'), :subscription_plans, :class => 'button'

app/views/shoppe/subscription_plans/_stripe_account.html.haml
= form_tag({controller: :subscription_plans, action: :stripe_account}, {method: :patch, id: :stripe_account_form}) do
  = select_tag :stripe_account, options_for_select(@stripe_accounts, @stripe_account), {class: 'chosen', onchange: 'this.form.submit();'}

app/views/shoppe/subscription_plans/edit.html.haml
- @page_title = t('shoppe.subscription_plans.subscription_plans')

= content_for :header do
  %p.buttons
    = link_to t('shoppe.subscribers.subscribers') , [@subscription_plan, :subscribers], :class => 'button green'
    = link_to t('shoppe.subscription_plans.back'), :subscription_plans, :class => 'button'
  %h2.orders= t('shoppe.subscription_plans.subscription_plans')

= render 'form'

app/views/shoppe/subscription_plans/index.html.haml
= stylesheet_link_tag 'shoppe_subscriptions/application'
= javascript_include_tag 'shoppe_subscriptions/application'

- @page_title = t('shoppe.subscription_plans.subscription_plans')

= content_for :header do
  %p.buttons
    = link_to t('shoppe.subscription_plans.sync'), :sync_subscription_plans, :class => 'button'
    = link_to t('shoppe.subscription_plans.new'), :new_subscription_plan, :class => 'button green'
  %h2.subscription_plans= t('shoppe.subscription_plans.subscription_plans')

= render 'shoppe/subscription_plans/stripe_account'

.table
  %table.data
    %thead
      %tr
        %th= t('shoppe.subscription_plans.amount')
        %th= t('shoppe.subscription_plans.interval')
        %th= t('shoppe.subscription_plans.interval_count')
        %th= t('shoppe.subscription_plans.name')
        %th= t('shoppe.subscription_plans.currency')
        %th= t('shoppe.subscription_plans.api_plan_id')
        %th= t('shoppe.subscription_plans.trial_period_days')
    %tbody
      - if @subscription_plans.empty?
        %tr.empty
          %td{:colspan => 7}= t('shoppe.subscription_plans.no_subscription_plans')
      - else
        - for subscription_plan in @subscription_plans
          %tr
            %td= link_to "#{number_to_currency subscription_plan.amount, unit: ISO4217::Currency.from_code(subscription_plan.currency).try(:symbol)}", [:edit, subscription_plan]
            %td= subscription_plan.interval
            %td= subscription_plan.interval_count
            %td= link_to subscription_plan.name, [:edit, subscription_plan]
            %td= subscription_plan.currency
            %td= subscription_plan.api_plan_id
            %td= subscription_plan.trial_period_days

app/views/shoppe/subscription_plans/new.html.haml
- @page_title = t('shoppe.subscription_plans.subscription_plans')

= content_for :header do
  %p.buttons= link_to t('shoppe.subscription_plans.back'), :subscription_plans, :class => 'button'
  %h2.delivery_services= t('shoppe.subscription_plans.subscription_plans')
= render 'form'

app/views/shoppe/subscription_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @subscription_plan.amount %>
</p>

<p>
  <strong>Interval:</strong>
  <%= @subscription_plan.interval %>
</p>

<p>
  <strong>Interval count:</strong>
  <%= @subscription_plan.interval_count %>
</p>

<p>
  <strong>Name:</strong>
  <%= @subscription_plan.name %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @subscription_plan.currency %>
</p>

<p>
  <strong>Trial period:</strong>
  <%= @subscription_plan.trial_period_days %>
</p>

<%= link_to 'Edit', edit_subscription_plan_path(@subscription_plan) %> |
<%= link_to 'Back', subscription_plans_path %>